### ISSUE TITLE
meta: docs wiki to docs

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-docs#68]
Check [the additions](https://github.com/mathjax/MathJax-docs/wiki/Docs.mathjax.org-additions) and [the improvements](https://github.com/mathjax/MathJax-docs/wiki/Docs.mathjax.org-improvements).

Use this issue to keep track of those that can move up to the docs.
- [ ] [Slimming-down guide](https://github.com/mathjax/MathJax-docs/wiki/Guide%3A-reducing-size-of-a-mathjax-installation)
- [ ] [Web-based editors](https://github.com/mathjax/MathJax-docs/wiki/List-of-web-based-math-editors)
- [ ] [Math-enabled screen-readers](https://github.com/mathjax/MathJax-docs/wiki/List-of-math-enabled-screen-readers)
- [ ] [CDN FAQs](https://github.com/mathjax/MathJax-docs/wiki/Cdn-Q%26A)

**Comment by pkra** [comment]
This is from ancient history. I don't think it's very relevant anymore.
