### ISSUE TITLE
2.5 release work

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-docs#78]
* [x] Update the https://github.com/mathjax/MathJax/wiki/Documentation-update-process
  * [x] create 2.5 branch
  * [ ] merge 2.5 branch into master -- #83
  * [x] Create What's New page
* [x] CommomHTML work
  * [x] document new CommonHTML output
  * [x] document CHTML-Preview extension
  * [x] update combined configuration page.
* [x] document MathML extensions 
  * [x] Content MathML extension (in particular, customization)
  * [x] mml3 extension
  * [x] update MathML.rst  -- #69
* [x] Tweak Getting Started
* [x] document handle-floats -- #84
* [x] document attribute preservation -- https://github.com/mathjax/MathJax/issues/860
* [x] update whats-new with bugs that came in during the beta run

* document clearing listeners -- https://github.com/mathjax/MathJax/issues/693 =>pushing this out of the release.

**Comment by pkra** [comment]
Thanks for the review, @dpvc. I've pushed the corrections.
